### ISSUE TITLE
トークンを削除ごグループ画面に戻ったら古い画面が残っている

### ISSUE THREAD

**Issue by dolfalf** [vkdlxh/SimpleDocbase#101]
再現手順
1. グループ画面から１つのグループを選択します。
2. メモ画面へ遷移します。
3. 設定画面に遷移し、トークンを削除します。
4. グループタブに戻る
5. 古い画面のままです。

仕様的には、
- グループタブの画面は全てトークンチェックが常に必要になる
- トークンがなかった場合、NavigationVCのTop画面に遷移させ、初期化させる必要がある。

**Comment by vkdlxh** [comment]
対応しました。
