### ISSUE TITLE
ViewControllerのデータの表示について

### ISSUE THREAD

**Issue by dolfalf** [vkdlxh/SimpleDocbase#11]
https://github.com/vkdlxh/SimpleDocbase/blob/fac77787efd35977022193e21f603cb5eac7ded9/SimpleDocbase/Controller/GroupViewController.swift#L47

なぜviewDidLoad()で値を取得すると思っているんですか。viewDidLoad()でrequestを投げても非同期のためここでは値が取得できません。delegateメソッドで渡すように実装したらそのメソッドから値を受け取り、データをTableViewのdatasourceへセットする。そしてTableViewのreloadすると画面に表示されるはずです。

**Comment by vkdlxh** [comment]
わかりました。delegateとdatasourceをもっと勉強します。
