### ISSUE TITLE
[不具合]グループ画面を開くとログイン画面が背景になっている

### ISSUE THREAD

**Issue by dolfalf** [vkdlxh/SimpleDocbase#129]
すでにログインした状態で、グループタブを開くと
ロード中に（グループ一覧を取得する前）ログイン画面が表示されている

ロード中には空白をするようにログインコントロールを隠してください。
（各コントロールをhiddenにするか、空白Viewで隠すか）

**Comment by vkdlxh** [comment]
対応しました。ご確認お願いします。

**Comment by dolfalf** [comment]
確認しました。
