### ISSUE TITLE
[不具合]ロード中のHUDが画面の真ん中ではない

### ISSUE THREAD

**Issue by dolfalf** [vkdlxh/SimpleDocbase#131]
タイトルの通りです。機種をチェックしてそれぞれ真ん中になるように修正してください。
特にiPhoneXの表示に気をつけてください。
場合によってバージョンことに分岐処理が必要かもしれませんね。

**Comment by vkdlxh** [comment]
対応します。

**Comment by vkdlxh** [comment]
ゼウンさんの確認を受けて対応しません。

**Comment by dolfalf** [comment]
了解です。Closeします。
