### ISSUE TITLE
4インチ端末で「アカウントを作成」画面の大体の文言が途切れて表示される

### ISSUE THREAD

**Issue by Lee-junha** [vkdlxh/SimpleDocbase#139]
下記画像の通りです。
![simulator screen shot - iphone se - 2018-02-03 at 02 32 24](https://user-images.githubusercontent.com/8198563/35746628-be61b580-088a-11e8-893f-9fa79444fe8e.png)

**Comment by vkdlxh** [comment]
このバグは前探して修正しました。
申し訳ありませんが、もう一度ご確認お願いできますか？
下記画像はiPhone SEの画像です。
![simulator screen shot - iphone se - 2018-02-04 at 18 53 53](https://user-images.githubusercontent.com/23257736/35776294-131c5dde-09dd-11e8-9a3d-a3f833e84998.png)

**Comment by Lee-junha** [comment]
自分が再現した環境は Xcode9.2 & iPhoneSE（11.2）です。
同じiPhoneSE（10.3.1）で起動したら、正常に表示されることを確認しました。

**Comment by vkdlxh** [comment]
Xcode9.2 & iPhoneSE（11.2）の環境に変更して確認しましたがバグが見つかりません。。
申し訳ありませんが、どのように確認するとバグがでる環境を作られますか？

**Comment by Lee-junha** [comment]
すみません、本件ですが自分のcocoaPodsのバージョンが古いので発生したようです。
1.1.1　→　1.3.0に上げたら直りました。なのでクローズします。すみませんでした。
