### ISSUE TITLE
リクエストの処理について

### ISSUE THREAD

**Issue by dolfalf** [vkdlxh/SimpleDocbase#18]
https://github.com/vkdlxh/SimpleDocbase/blob/66343480a1c9ee18a205073aae9c215a48a08861/SimpleDocbase/Controller/Group/GroupViewController.swift#L82

チームを取得してすぐgroupListのリクエストを発行していますが、
このようなsequence処理が必要なリクエストは画面側で実装するのはよくないです。

Reqeustクラスで１つのメソッドを作り順番にリクエストを発行して最後の結果を返すように実装してください。
その場合リクエストの同期処理が必要なので下記のリンクを参考してください。

https://qiita.com/koji-nishida/items/14fda04b586263a47e73

**Comment by vkdlxh** [comment]
Semaphoreを利用して同期処理を簡単に確認しましたが、
ゼウンさんの目指すことはRequestファイルに別途のメソットを作ってViewControllerに
実装しようとおっしゃるんですか？
例えば、`func getGroupNameFromTeam()`みたいな形でしょうか？

**Comment by dolfalf** [comment]
そうですね。ViewControllerで実装するのではなく、リクエスト処理を全てRequestクラスにまとめてほしいです。
要するに画面側（ViewController）はメソッドを呼び出し結果を取得するような仕組みにしてほしいです。

**Comment by vkdlxh** [comment]
https://github.com/vkdlxh/SimpleDocbase/blob/3a7a7c469545e646c862bd7d7701b1516151826b/SimpleDocbase/Request/Request.swift#L39-L52

上記にように実装してみましたが、こんな形が合いますか？
そしてmainQueueに何を実装するのか良くわかりません。

**Comment by dolfalf** [comment]
間違っています。
`self.getTeamList() `の結果は取得してから`self.groupList(domain: domain)` の処理ではないですか。
ソースをみた限り、順番に処理しないようですが。。

break pointかlogを出力してどのような順番で実行されるか確認してください。

**Comment by vkdlxh** [comment]
break pointで順番を確認します。

**Comment by vkdlxh** [comment]
asyncをsyncに変更しました。これが合うのですか？

**Comment by dolfalf** [comment]
ちょっと違います。semaporeを使ってできると思います。

**Comment by dolfalf** [comment]
上記のSemapreの話は忘れてください。
delegateパターンになっているのでRequestクラスを分離し順番に処理するように実装すればOKです。

**Comment by vkdlxh** [comment]
最初にteamのdomainが必要した理由はただ初期にUserDefalutにdomainの値があるかの確認だけでした。
https://github.com/vkdlxh/SimpleDocbase/blob/92ace4c7343b3048cda2bfcf8da271a2ea2bff71/SimpleDocbase/Request/GroupRequest.swift#L23-L31
それてあえてdelegateでチームのdomainを取得しないで、Requestクラスを分離して`GroupRequest`に新しく`func getGroupFromTeam()`クラスで一緒に処理するメソットを実装しました。
こんな形でも宜しいですか？

https://github.com/vkdlxh/SimpleDocbase/blob/92ace4c7343b3048cda2bfcf8da271a2ea2bff71/SimpleDocbase/Request/GroupRequest.swift#L13-L40

**Comment by dolfalf** [comment]
それで問題なく動ければ問題ないです。
もし、domainが必要な場合、保存されてない時はalertを表示する。ユーザーから登録するようにする方法もありますね。

**Comment by vkdlxh** [comment]
かしこまりました。アドバイスありがとうございます。
