### ISSUE TITLE
Life cycleを考えてください。

### ISSUE THREAD

**Issue by dolfalf** [vkdlxh/SimpleDocbase#19]
https://github.com/vkdlxh/SimpleDocbase/blob/66343480a1c9ee18a205073aae9c215a48a08861/SimpleDocbase/Controller/Group/MemoListViewController.swift#L49

上記の処理はUIのイベントを登録する処理です。毎回、登録する必要があるかどうか考えてみてください。

**Comment by vkdlxh** [comment]
かしこ増しました。
宜しいLife Cycleを利用します。

**Comment by dolfalf** [comment]
了解しました。

***
日本語を訂正します。
>かしこ増しました。
宜しいLife Cycleを利用します。

かしこまりました。
正しいLife Cycleで実装します。

**Comment by vkdlxh** [comment]
日本語のアドバイスありがとうございます。

**Comment by dolfalf** [comment]
対応完了したら「対応しました」などでコメントください。issueをCloseします。

**Comment by vkdlxh** [comment]
かしこまりました。
対応しました。
