### ISSUE TITLE
ViewDidLoad()の中の関数を利用する方法について

### ISSUE THREAD

**Issue by vkdlxh** [vkdlxh/SimpleDocbase#2]
お疲れ様です。

グループリストのtableViewのcellの内容を実際のデータで利用してみようとしました。
思ったイメージは下記と同じです。

最初にアプリが実行されてGroupTableViewControllerのViewDidLoad()が呼び出す時、
if文でグループリストに必要なdomainを持っているのを確認します。
設定からチームを選択したのがないで状態(最初の実行)の時は基本のチームのグループリストを
呼び出すためにまずはgetTeamList()の関数を呼び出します。
teamDomains配列にチームのdomainを入れて0番目の値を持ってdefaultDomainに入れます。
生成されたdefaultDomainをgroupList(domain:)関数に入れて
グループリストを持ってくるのが目標です。

<img width="1440" alt="2017-10-27 18 42 06" src="https://user-images.githubusercontent.com/23257736/32098765-b5c80cc4-bb48-11e7-9ad8-2a0274a1e34e.png">

テストの目的に作ったボタンをクリックした時はチームのdomainを持って配列に入れられます。
ですが、ViewDidLoad()が実行された時、すぐ関数を呼び出して配列を作って入れたいですが、それができません。 
下記が上記の内容のコードです。

https://github.com/vkdlxh/SimpleDocbase/blob/b47e15cb63877019a78e7366840dff5146cc87cd/SimpleDocbase/Controller/GroupTableViewController.swift#L30-L40

**Comment by dolfalf** [comment]
考えるポイントは３つですね。
* データが非同期で取得した場合の処理
* ViewDidLoad()のようなControllerのライフサイクル
* サーバーからデータを取得できたらどうするか

## まず、データの取得処理について
サーバーにあるデータを取得するのはネットワーク状況により取得するのに時間がかかったり、もしかしたら取得できない場合もあります。
そのため、データを取得に失敗したメッセージや取得する間に表示するメッセージが必要だと思います。
（viewDidLoadではローカルで何かをキャシューしない限り表示できないのは当然です。）
他のアプリのUIを参考に考えてください。

##  ViewDidLoad()のようなControllerのライフサイクルについて
データを取得するタイミングを考える必要があります。
`ViewDidLoad`はおそらく画面がロードする時に1回のみ呼ばれます。（知っていると思いますが。。）
例えば、他のアプリを使う操作をしたとしましょう。
そしたら、アプリはバックグラウンドに入ります。その後、またアプリへ戻った場合、すでに画面がロードされている状態なので`ViewDidLoad`は呼ばれません。結果として古いデータが表示されるままになります。取得処理はLife Cycleを考えた上でとこで実装するか考えてください。

##  サーバーからデータを取得できたらどうするかについて
画面を更新する必要がありますのでdatasorceにセットし、TableViewの`reloadData`を呼び出しすればメソッドの名前の通りdelegateメソッドなどが再び呼ばれて画面に表示されると思います。

**Comment by dolfalf** [comment]
`request.getTeamList()` から取得するデータを画面側に渡す方法はいくつかありますが、PRしますのでご参考ください。

**Comment by vkdlxh** [comment]
アドバイスありがとうございます。参考してします。
