### ISSUE TITLE
データの持ち方について

### ISSUE THREAD

**Issue by dolfalf** [vkdlxh/SimpleDocbase#20]
https://github.com/vkdlxh/SimpleDocbase/blob/66343480a1c9ee18a205073aae9c215a48a08861/SimpleDocbase/Controller/Group/DetailMemoViewController.swift#L13

この画面は詳細画面です。表示するために必要なデータがなんなのか考えてください。
全て持つ必要はないと思います。
いらないデータを「もし、分からないから」、「あとで必要になるかも」などでしておくと混乱するし、時間が経つと分からなくなります。
きちんと目的に合わせてデータを持ちましょう。

**Comment by vkdlxh** [comment]
<img width="774" alt="2017-11-08 15 14 41" src="https://user-images.githubusercontent.com/23257736/32534193-cc7c9f7c-c497-11e7-8b2b-901989c99ed2.png">
配列からAnyタイプに変更して実装しました。

**Comment by dolfalf** [comment]
AnyタイプではなくMemoタイプで良いではないでしょうか。

**Comment by vkdlxh** [comment]
`DetailMemoViewController`にMemoタイプでパラメーターをどのように実装するか良くできなくてAnyタイプでしました。Memoタイプでやってみます。

**Comment by dolfalf** [comment]
パラメータでデータを渡すことについて理解してないようですね。渡す側ではどの型で渡すかによって渡される側の型が決まるはずです。

**Comment by vkdlxh** [comment]
`var memo = Memo()`みたいにパラメータを実装してそのパラメータに渡すのではないですか？

**Comment by dolfalf** [comment]
質問の意味が読めません。オフ会で話しましょう。

**Comment by vkdlxh** [comment]
わかりました。すみません。

**Comment by dolfalf** [comment]
これは解決ですね。クローズします。
