### ISSUE TITLE
メモ投稿する時の画面の動きについて

### ISSUE THREAD

**Issue by dolfalf** [vkdlxh/SimpleDocbase#22]
https://github.com/vkdlxh/SimpleDocbase/blob/66343480a1c9ee18a205073aae9c215a48a08861/SimpleDocbase/Controller/Group/WriteMemoViewController.swift#L57

メモ投稿の結果を待たずに画面を閉じても良いですか。
もし、投稿に失敗した場合も想定してください。

**Comment by vkdlxh** [comment]
https://github.com/vkdlxh/SimpleDocbase/blob/06129571cdb315e61a4ed03351681bba1e9f40fe/SimpleDocbase/Controller/Group/MemoListViewController.swift#L26-L27

Requestみたいに`WriteMemoListViewController`にdelegateを作りましたが、
`MemoListViewController`でModalViewをコントロールができません。

modal Viewで登録ボタンをタプすればMemoListViewControllerが確認してdismissしたいんですが、
どのようにすればいいかわかりません。

`Dodal View Delegate Error`というcommitをしました。
（DodalはModalのミス・パンチです。）

**Comment by vkdlxh** [comment]
解決しているところです。
自分で直接やってみます。

**Comment by vkdlxh** [comment]
解決してpushしました。

**Comment by dolfalf** [comment]
ソースをみている限り間違っています。
`WriteMemoListViewController`は閉じるタイミングがわかります。そのタイミングを`MemoListViewController `に教える。教えるためにdelegateパターンを使うのです。

結果、閉じる処理は`MemoListViewController `で行います。もう少し考えてください。大事なところです。

**Comment by dolfalf** [comment]
失礼しました。私の勘違いです。正しく実装されているのでOKです。
ネーミングだけ気をつけてください。
