### ISSUE TITLE
pagingについて

### ISSUE THREAD

**Issue by vkdlxh** [vkdlxh/SimpleDocbase#35]
お疲れ様です。
現在のページングの処理は
Memoリストを取得するRequestで
URLを

https://github.com/vkdlxh/SimpleDocbase/blob/90301033051acde0c1f92c73adbf0fc91849b115/SimpleDocbase/Request/ACAMemoRequest.swift#L13-L15

上記の形で取得しています。
`per_page=20`を通じて20個のメモを取得します。
pageNumは1から始めますので既定値を1に実装して`UIScrollViewDelegate`の
`scrollViewDidEndDragging`のメソッドを通じて+=1づつ上げています。

https://github.com/vkdlxh/SimpleDocbase/blob/90301033051acde0c1f92c73adbf0fc91849b115/SimpleDocbase/Controller/Group/MemoListViewController.swift#L161-L182

まずは動作はできますが、気になる部分がありますか？

**Comment by dolfalf** [comment]
API確認しました。全さんの実装で問題ないです。
`20`の数字だけは定数化してください。

**Comment by vkdlxh** [comment]
かしこまりました。`perPage`を追加しました。
https://github.com/vkdlxh/SimpleDocbase/blob/e43e591f8d27bed41d16ade8fc60e8351279ae1c/SimpleDocbase/Controller/Group/MemoListViewController.swift#L20-L22

**Comment by dolfalf** [comment]
OKです。Closeしてください。
