### ISSUE TITLE
止まらないHUDについて

### ISSUE THREAD

**Issue by vkdlxh** [vkdlxh/SimpleDocbase#36]
https://github.com/vkdlxh/SimpleDocbase/blob/729d5be365e18efdb2a509e92f07b5998ca72cd8/SimpleDocbase/Controller/Group/GroupViewController.swift#L30-L41

シミュレーターを初期化してからアプリを実行すると最初にTokenKeyが無くてAlertが出てHUDも問題なく消えます。
ですが、そこでTokenKeyを設定しないで、キャンセルして他のViewに移動してGroupに戻ったら
またWillAppearが呼び出してHUDが呼び出します。
私が考えたのはRequestのクロージャが終わらないためにメーンスレッドが実行しませんのでdismissが呼び出さないと思っていますが。。

どのように処理をすれば宜しいですか？

**Comment by vkdlxh** [comment]
RequestのCompletionの値をnilにくれる部分を実装して解決しました。

https://github.com/vkdlxh/SimpleDocbase/blob/9b67967b0ca6db040e6ff02a754599ae574f82fd/SimpleDocbase/Request/ACAGroupRequest.swift#L49-L52

**Comment by dolfalf** [comment]
今の処理だと画面が表示する時に表示される実装になっています。
まずTokenがないと使えない画面、Tokenがなくても使える画面を切り分けてください。
そして、チェックを入れること。いろいろなパターンがあると思います。(Homeボタン、電話、タブ移動などなど)

HUDは本来リクエストを発行する時からレスポンスが返すところまで表示するものだから、その時に書いてください。（失敗の時、リスポンスが来る前に画面遷移の場合を考慮してください。）

**Comment by dolfalf** [comment]
ここは日本語の訂正です。

> シミュレーターを初期化してからアプリを実行すると**最初はTokenKeyが無いからAlertが表示され**HUDも問題なく消えます。
> ですが、**TokenKeyを設定しないでキャンセルし、他の画面に移動してGroupに戻ったら**
> またWillAppearが**呼び出されてHUDが呼ばれます。**
> 私が考えたのはRequestのクロージャが終わらない**と**メーンスレッドが実行しませんのでdismissが**呼べない**と思っていますが。。
> 
> どのように処理をすれば宜しいですか？

***

一応修正しましたが、やっぱり説明が長くなると分かりにくくなります。この場合少し整理した方が良いと思います。

TokenKeyを設定しないで画面を移動をすると再びHUDが表示されてしまう問題があります。
どのように処理をすれば宜しいですか？

- 再現手順
1. シミュレーターを初期化
2. TokenKeyを入力Alertが表示されたらキャンセル
3. 他のタブに移動する
4. Groupに戻る
5. WillAppearが呼ばれHUDが表示されてしまう

**Comment by vkdlxh** [comment]
> まずTokenがないと使えない画面、Tokenがなくても使える画面を切り分けてください。

現在ははTokenKeyがない場合、SectionとTableViewが表示されなく実装しています。
TokenKeyがある場合とない場合との画面を切り分けるのはViewControllerを作つくるとおっしゃるのですか？

**Comment by dolfalf** [comment]
>ViewControllerを作つくるとおっしゃるのですか？

いいえ。Tokenが利用される画面にチェック処理を入れることです。

**Comment by dolfalf** [comment]
解決出来たらクローズお願いします。
