### ISSUE TITLE
デザインについて（アドバイス）

### ISSUE THREAD

**Issue by dolfalf** [vkdlxh/SimpleDocbase#40]
デザイン的にできること、できないこと、色を設定しながら把握できたと思います。
いくつかPickupしますのでデザイン対応をお願いします。

- テキスト色について
Black, Gray, LigitGrayの３つの色で指定してください。テキストの重要度順です。さらに強調したい場合はフォントをBoldにしてください。
- ナビバー、タブについて
ナビバーの背景色にテマ色を設定してください。（タイトルのテキストはデフォルトで良いと思います。おそらくWhiteだと思います。）
タブのアイコンは色をつけない方が良さそうです。

- splash画面を追加（launch screen）
アプリを起動するときに表示されるsplash画面を追加して見てください。
デザインはお任せします。
[参考リンク１](http://tutlane.com/tutorial/ios/ios-launch-screen-splash-screen)
[参考リンク２](https://stackoverflow.com/questions/35593614/how-to-display-launch-image)

**Comment by vkdlxh** [comment]
かしこまりました。コメントの表示を追加しながら修正します。
