### ISSUE TITLE
やるべきことについて

### ISSUE THREAD

**Issue by dolfalf** [vkdlxh/SimpleDocbase#5]
- [x] Issueが解決できたら必ずCloseしてください。
- [x] TableViewControllerからの継承をUIViewControllerにしてください。
- [x] 不要なコードは削除してください。（私が書いたコメントも含める）
- [x] Modelを最小単位にしてください。（リストはモデルではありません。）
- [x] Controllerの名称にTableを削除してください。
- [x] タブことにフォルダ（グループ）を作成、storyboardも分けてください。

上記の内容で対応できるものは対応してチェックしてください。

**Comment by vkdlxh** [comment]
1. `タブことにフォルダ（グループ）を作成、storyboardも分けてください。`が
今したことの意味かよく分かりません。
ブランチにpushしました。確認してアドバイスお願いします。

2. そして、`TableViewControllerからの継承をUIViewControllerにしてください。`は
どのようにするのか理解ができません。アドバイスお願いします。

3. `リストはモデルではありません。`なら、リストはとこですか？

**Comment by dolfalf** [comment]
>タブことにフォルダ（グループ）を作成、storyboardも分けてください。が
今したことの意味かよく分かりません。
ブランチにpushしました。確認してアドバイスお願いします。

今は`main.storyboard`しかないと思いますが、3つのタブに機能がそれぞれ違うので３つのstoryboardを作る意味です。
例えば、`main.storyboard`, `group.storyboard`, `sheet.storyboard`, `setting.storyboard`ののように分けてください。
こちらを参考してください。
https://qiita.com/The_Shimon/items/2af23fab4a42ab7247ba

>そして、`TableViewController`からの継承を`UIViewController`にしてください。は
どのようにするのか理解ができません。アドバイスお願いします。

今`ViewController`は`TableViewController`を継承していますが、それをやめ、`UIViewController`にすることです。

>リストはモデルではありません。なら、リストはとこですか？

modelの直下のモデルクラスがXXXListになっています。これはモデルではありません。
リストを構成する最小単位のクラスがモデルです。

**Comment by vkdlxh** [comment]
1番はきちんと探してしたようです。

>今ViewControllerはTableViewControllerを継承していますが、それをやめ、UIViewControllerにすることです。

は継承を下記みたいにしなさいということですか？

<img width="786" alt="2017-10-30 17 27 53" src="https://user-images.githubusercontent.com/23257736/32161294-59a69a6c-bd98-11e7-893d-533115a90151.png">

**Comment by dolfalf** [comment]
その通りです。
なのでUIViewControllerを @IBOutletで宣言する必要になると思います。

ここからは理由です。
UITableViewを継承するとTableView以外にUIを使えなくなります。今のところこれで満たしていますが、機能を拡張する時にややこしくなるため、最初からUIViewControllerにするわけです。

**Comment by vkdlxh** [comment]
issue#5にpushしました。
モデル部分は最大限分けましたが、よく分からないて、アドバイスお願いします。

**Comment by dolfalf** [comment]
別途issueで書いています。参考にしてください。

**Comment by vkdlxh** [comment]
はい。わかりました。
