### ISSUE TITLE
WorkSheetItem貯蔵について

### ISSUE THREAD

**Issue by vkdlxh** [vkdlxh/SimpleDocbase#53]
@dolfalf 
お疲れ様です。

現在、オフ会でアドバイスを受けた通りにJSONからWorkSheetを呼び出して表示するようにしています。
WorkSheetは`workData`という固有のDateを使って、例えば201701みたいにフォーマットしてKeyに活用してJSONから探せます。
ですが、多数のItemの中で指定されたWorkSheetItemをJSONファイルから呼び出す方法と、そのItemだけJSONにまた貯蔵する方法が分かりません。

**Comment by dolfalf** [comment]
１つのJSONにする話をしたので１つのItemが変更されても全体にJSONファイルを更新する必要があります。
なので、Itemを修正されたら、メモリ上のモデルを更新し、それをそのままJSONで変換、保存するように実装してください。

***
ちなみに`貯蔵`の意味がわかりません。`実装`ではないですか。

**Comment by vkdlxh** [comment]
かしこまりました。
WorkSheetItemモデルの`beginTime`,`endTime`はDateではなくてただのIntで09:00みたいに実装しなければならないのですか？

**Comment by vkdlxh** [comment]
まずは作動できます。Closeしても宜しいですか？
