### ISSUE TITLE
トークン登録案内について

### ISSUE THREAD

**Issue by dolfalf** [vkdlxh/SimpleDocbase#57]
>TokenKeyを設定してください。

を
>DocBaseから「個人設定」->「基本設定」->「APIトークン」を作成して表示されたトークンを登録してください。

のように文言を変更してください。

タイトルの`Token`も`トークン`に変更してください。

> テスト環境
> テスト機種：iPhoneX
> iOSバージョン： 11.0

**Comment by vkdlxh** [comment]
#68 issueを対応しながら一緒に対応します。

**Comment by vkdlxh** [comment]
> DocBaseから「個人設定」->「基本設定」->「APIトークン」を作成して表示されたトークンを登録してください。

が長くて全部表示できません。どのようにしますか？

**Comment by vkdlxh** [comment]
まずはトークン登録画面で表示されるようにしました。

**Comment by dolfalf** [comment]
確認しました。
