### ISSUE TITLE
アプリ内の`TokenKey`文言について

### ISSUE THREAD

**Issue by dolfalf** [vkdlxh/SimpleDocbase#58]
アプリにTokenKeyになっているがDocBaseは「APIトークン」になっている。
DocBaseに合わせるように修正してください。

> テスト環境
> テスト機種：iPhoneX
> iOSバージョン： 11.0

**Comment by vkdlxh** [comment]
#68 issueを対応しながら一緒に対応します。

**Comment by vkdlxh** [comment]
対応しました。

**Comment by dolfalf** [comment]
だま対応してないところがあります。
全て「APIトークン」に合わせてください。
・トークン登録アラート
・設定画面のトークンタイトル

**Comment by vkdlxh** [comment]
すみません。また対応しました。

**Comment by dolfalf** [comment]
確認しました。
