### ISSUE TITLE
Requestのpropertyについて

### ISSUE THREAD

**Issue by dolfalf** [vkdlxh/SimpleDocbase#6]
https://github.com/vkdlxh/SimpleDocbase/blob/fac77787efd35977022193e21f603cb5eac7ded9/SimpleDocbase/Request/Request.swift#L20-L22

delegateパターンを使うとこのpropertyはReqeustクラスで要りません。delegateパターンでデータを渡しているので画面のメソッドから値を取得し、TableViewのdatasourceにセットしてください。

**Comment by vkdlxh** [comment]
かしこまりました。やってみます。
