### ISSUE TITLE
グループ画面のSectionタイトルについて

### ISSUE THREAD

**Issue by dolfalf** [vkdlxh/SimpleDocbase#60]
上にするロールをするとSectionタイトルの裏側のセルが見えてしまうため見た目でよくない。
デザイン対応で検討する必要がある

> テスト環境
> テスト機種：iPhoneX
> iOSバージョン： 11.0

**Comment by vkdlxh** [comment]
対応します。

**Comment by vkdlxh** [comment]
対応しました。

**Comment by dolfalf** [comment]
確認しました。
