### ISSUE TITLE
メモの新規登録のチェック処理がない

### ISSUE THREAD

**Issue by dolfalf** [vkdlxh/SimpleDocbase#62]
タイトル、メモの入力は必須なので入力チェックを入れる必要があります。

未入力の場合は、
「タイトルを入力してください。」、「メモを入力してください。」
のアラートを表示する仕様で良いと思います。

**Comment by vkdlxh** [comment]
対応します。

**Comment by vkdlxh** [comment]
#86 対応しました。確認してください。

**Comment by dolfalf** [comment]
確認しました。
