### ISSUE TITLE
勤怠表の削除について

### ISSUE THREAD

**Issue by dolfalf** [vkdlxh/SimpleDocbase#75]
削除することにより、何も表示しなくなったら「勤務表がありません。」のような文言を真ん中に表示してください。

**Comment by vkdlxh** [comment]
もう削除して勤務表がなくなったら「データがありません。」のような文言が出ます。
確認してください。
それで「データがありません。」を「勤務表がありません。」に変更しました。

**Comment by vkdlxh** [comment]
対応します。

**Comment by vkdlxh** [comment]
まだ対応中です。

**Comment by vkdlxh** [comment]
対応しました。

**Comment by dolfalf** [comment]
確認しました。
