### ISSUE TITLE
存在する勤務表の年と月を入力してOKタップすると上書きのアラートが表示しない

### ISSUE THREAD

**Issue by dolfalf** [vkdlxh/SimpleDocbase#76]
存在する勤務表の年と月を入力してOKタップすると上書きのアラートが表示しない。
トークンを登録してないのみ発生するようです。

テスト機種
iPhoneX
iOS11

**Comment by vkdlxh** [comment]
対応します。

**Comment by vkdlxh** [comment]
iPhoneXで確認しましたが、上書きアラートが出ます。
トークンをとうろぅしてない場合にもテストしてみましたが、アラートが出ます。
もう一回確認お願いします。

**Comment by dolfalf** [comment]
確認しました。確かアラート表示されますね。何か違うパターンで発生するかもしれません。
一応、このissueはクローズします。
