### ISSUE TITLE
データの渡し方が間違っています。

### ISSUE THREAD

**Issue by dolfalf** [vkdlxh/SimpleDocbase#8]
https://github.com/vkdlxh/SimpleDocbase/blob/fac77787efd35977022193e21f603cb5eac7ded9/SimpleDocbase/Request/Request.swift#L77

このようにpropertyにセットして画面から参照するのダメです。特に非同期で値が取得されるのでここでセットするタイミング、画面から取得するタイミングを合わせることができません。
なので、delegateパターンかclouserを利用して渡すのです。

**Comment by vkdlxh** [comment]
かしこまりました。delegateを使ってします。
