### ISSUE TITLE
勤務表のアップロードエラー

### ISSUE THREAD

**Issue by dolfalf** [vkdlxh/SimpleDocbase#81]
勤務表グループを登録したにも関わらず、アップロードできない

再現手順
1. 勤務表グループを登録しないまま勤務表タブに遷移
2. アップロードボタンをタップ
3. エラーメッセージが表示されたら閉じて設定画面へ遷移
4. 勤務表グループ登録し、勤務表タブに戻る
5. アップロードボタンをタップ

勤務表画面からリストへ一旦戻り、勤務表画面に遷移するとアップロードできる

**Comment by vkdlxh** [comment]
対応します。

**Comment by vkdlxh** [comment]
対応しました。

**Comment by vkdlxh** [comment]
対応しました。

**Comment by dolfalf** [comment]
まだ直ってないようですが。。。もう一度確認してください。

**Comment by vkdlxh** [comment]
もう一度確認しましたので、色んなバグがありました。対応します。

**Comment by vkdlxh** [comment]
グループ画面を経ないで設定画面から勤怠管理画面にすぐ遷移する時の問題
1. チームを選択して勤務表タブに遷移
2. またグループタブに遷移
3. 設定画面に遷移して
4. 勤務表グループ登録してから勤務表タブに戻る
5. アップロードボタンをタップ
6. 勤怠管理グループを設定したけど関わらず、アップロードできない

勤怠管理グループを登録してもアップロードができない問題
チームを変更して勤怠管理グループを登録した場合はすぐアップロードができるけど、
最初にトークンを登録して勤怠管理グループを登録した場合はすぐアップロードができない

**Comment by vkdlxh** [comment]
対応しました。

**Comment by dolfalf** [comment]
まだ、なおってないです。
そして、トークン登録直後「勤務表グループ」を選択しようとするとリストが出てごない現象もあります。
再現できなかったら、オフ会で再現してみます。

**Comment by dolfalf** [comment]
一旦、グループ画面でグループリストを表示させると直りますね。

**Comment by vkdlxh** [comment]
>そして、トークン登録直後「勤務表グループ」を選択しようとするとリストが出てごない現象もあります。

対応しました。

**Comment by vkdlxh** [comment]
また対応しました。確認お願いします。
