### ISSUE TITLE
モデルについて

### ISSUE THREAD

**Issue by dolfalf** [vkdlxh/SimpleDocbase#9]
モデルではないクラスです。削除してください。（ViewControllerのpropertyのようなものです）
- GroupList.swift
- TeamList.swift
- SettingData.swift
- SettingItem.swift
- SettingMenu.swift

**Comment by vkdlxh** [comment]
上記のクラスを削除したら、あのクラスの機能はViewControllerの中で作動するようにするのですか？

**Comment by vkdlxh** [comment]
`TeamList.swift`の機能を下記みたいにdelegate部分に入れましたが、この方法が合いますか？
<img width="577" alt="2017-10-31 15 06 25" src="https://user-images.githubusercontent.com/23257736/32209729-21597516-be4d-11e7-961e-d1d540dc7079.png">

**Comment by dolfalf** [comment]
違います。モデルの生成はRequestクラスで作成し配列の形で画面側に渡してください。

**Comment by vkdlxh** [comment]
かしこまりました。Requestクラスで作成します。
